// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	entities "RequestTasker/internal/domian/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RequestTaskerMock is an autogenerated mock type for the RequestTasker type
type RequestTaskerMock struct {
	mock.Mock
}

// RegisterTask provides a mock function with given fields: ctx, task
func (_m *RequestTaskerMock) RegisterTask(ctx context.Context, task entities.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for RegisterTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRequestTaskerMock creates a new instance of RequestTaskerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestTaskerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestTaskerMock {
	mock := &RequestTaskerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
