// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	entities "RequestTasker/internal/domian/entities"

	mock "github.com/stretchr/testify/mock"
)

// TaskResultRepositoryMock is an autogenerated mock type for the TaskResultRepository type
type TaskResultRepositoryMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *TaskResultRepositoryMock) Create(_a0 entities.TaskResult) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.TaskResult) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByTaskID provides a mock function with given fields: taskID
func (_m *TaskResultRepositoryMock) GetByTaskID(taskID int64) (entities.TaskResult, error) {
	ret := _m.Called(taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTaskID")
	}

	var r0 entities.TaskResult
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (entities.TaskResult, error)); ok {
		return rf(taskID)
	}
	if rf, ok := ret.Get(0).(func(int64) entities.TaskResult); ok {
		r0 = rf(taskID)
	} else {
		r0 = ret.Get(0).(entities.TaskResult)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskResultRepositoryMock creates a new instance of TaskResultRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskResultRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskResultRepositoryMock {
	mock := &TaskResultRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
