// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	entities "RequestTasker/internal/domian/entities"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TaskRepositoryMock is an autogenerated mock type for the TaskRepository type
type TaskRepositoryMock struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, task
func (_m *TaskRepositoryMock) Create(ctx context.Context, task entities.Task) (*entities.Task, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Task) (*entities.Task, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Task) *entities.Task); ok {
		r0 = rf(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, taskID
func (_m *TaskRepositoryMock) Get(ctx context.Context, taskID int64) (*entities.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPublicID provides a mock function with given fields: ctx, publicId
func (_m *TaskRepositoryMock) GetByPublicID(ctx context.Context, publicId uuid.UUID) (*entities.Task, error) {
	ret := _m.Called(ctx, publicId)

	if len(ret) == 0 {
		panic("no return value specified for GetByPublicID")
	}

	var r0 *entities.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Task, error)); ok {
		return rf(ctx, publicId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Task); ok {
		r0 = rf(ctx, publicId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, publicId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskRepositoryMock creates a new instance of TaskRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepositoryMock {
	mock := &TaskRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
