version: "3"

tasks:
  generate-api:
    cmds:
      - oapi-codegen -generate types,server,strict-server,spec -package api ./openapi/api.yml > ./internal/app/api/api.gen.go
  generate-mock:
    cmds:
      - go generate ./internal/domian/entities

# setup dependencies

# clean dependencies

# run

# stop

# migration

# clean db

# test

# test integration
