version: "3"

tasks:
  generate_api:
    cmds:
      - oapi-codegen -generate types,server,strict-server,spec -package api ./openapi/api.yml > ./internal/app/api/api.gen.go
      
# generate mocks

# setup dependencies

# clean dependencies

# run

# stop

# migration

# clean db

# test

# test integration
