version: "3"

tasks:
  generate-api:
    cmds:
      - oapi-codegen -generate types,server,strict-server,spec -package api ./openapi/api.yml > ./internal/app/api/api.gen.go
  generate-mock:
    cmds:
      - go generate ./internal/domian/entities
  build:
    cmds:
    - go build -o ./bin ./cmd/
  test-db:
    cmds:
    - go test -v -parallel 4 RequestTasker/internal/infrastructures/mysql

# setup dependencies

# clean dependencies

# run

# stop

# migration

# clean db

# test

# test integration
