// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// Defines values for HttpMethod.
const (
	DELETE  HttpMethod = "DELETE"
	GET     HttpMethod = "GET"
	HEAD    HttpMethod = "HEAD"
	OPTIONS HttpMethod = "OPTIONS"
	PATCH   HttpMethod = "PATCH"
	POST    HttpMethod = "POST"
	PUT     HttpMethod = "PUT"
)

// Defines values for TaskStatus.
const (
	Done      TaskStatus = "done"
	Error     TaskStatus = "error"
	InProcess TaskStatus = "in_process"
	New       TaskStatus = "new"
)

// GetTaskResponse defines model for GetTaskResponse.
type GetTaskResponse struct {
	// Headers Headers array from 3rd-party service response
	Headers *map[string]interface{} `json:"headers,omitempty"`

	// HttpStatusCode HTTP status code of the 3rd-party service response
	HttpStatusCode *int `json:"httpStatusCode,omitempty"`

	// Id Unique ID of the task
	Id string `json:"id"`

	// Length Content length of 3rd-party service response
	Length *int       `json:"length,omitempty"`
	Status TaskStatus `json:"status"`
}

// HttpMethod defines model for HttpMethod.
type HttpMethod string

// InvalidRequestPayload defines model for InvalidRequestPayload.
type InvalidRequestPayload struct {
	// Message Invalid request payload
	Message string `json:"message"`
}

// TaskRequest defines model for TaskRequest.
type TaskRequest struct {
	// Body Request body payload
	Body *string `json:"body,omitempty"`

	// Headers Headers for the HTTP request
	Headers *map[string]interface{} `json:"headers,omitempty"`
	Method  HttpMethod              `json:"method"`

	// Url URL of the 3rd-party service
	Url string `json:"url"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// PostTaskJSONRequestBody defines body for PostTask for application/json ContentType.
type PostTaskJSONRequestBody = TaskRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new task for HTTP request to 3rd-party service
	// (POST /task)
	PostTask(ctx echo.Context) error
	// Get the status of a task
	// (GET /task/{id})
	GetTaskId(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostTask converts echo context to params.
func (w *ServerInterfaceWrapper) PostTask(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTask(ctx)
	return err
}

// GetTaskId converts echo context to params.
func (w *ServerInterfaceWrapper) GetTaskId(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTaskId(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/task", wrapper.PostTask)
	router.GET(baseURL+"/task/:id", wrapper.GetTaskId)

}

type PostTaskRequestObject struct {
	Body *PostTaskJSONRequestBody
}

type PostTaskResponseObject interface {
	VisitPostTaskResponse(w http.ResponseWriter) error
}

type PostTask201JSONResponse struct {
	// Id Generated unique ID for the task
	Id string `json:"id"`
}

func (response PostTask201JSONResponse) VisitPostTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostTask400JSONResponse InvalidRequestPayload

func (response PostTask400JSONResponse) VisitPostTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostTask401Response struct {
}

func (response PostTask401Response) VisitPostTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type PostTask500Response struct {
}

func (response PostTask500Response) VisitPostTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

type GetTaskIdRequestObject struct {
	Id string `json:"id"`
}

type GetTaskIdResponseObject interface {
	VisitGetTaskIdResponse(w http.ResponseWriter) error
}

type GetTaskId200JSONResponse GetTaskResponse

func (response GetTaskId200JSONResponse) VisitGetTaskIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskId400JSONResponse InvalidRequestPayload

func (response GetTaskId400JSONResponse) VisitGetTaskIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTaskId401Response struct {
}

func (response GetTaskId401Response) VisitGetTaskIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(401)
	return nil
}

type GetTaskId404Response struct {
}

func (response GetTaskId404Response) VisitGetTaskIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetTaskId500Response struct {
}

func (response GetTaskId500Response) VisitGetTaskIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(500)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new task for HTTP request to 3rd-party service
	// (POST /task)
	PostTask(ctx context.Context, request PostTaskRequestObject) (PostTaskResponseObject, error)
	// Get the status of a task
	// (GET /task/{id})
	GetTaskId(ctx context.Context, request GetTaskIdRequestObject) (GetTaskIdResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostTask operation middleware
func (sh *strictHandler) PostTask(ctx echo.Context) error {
	var request PostTaskRequestObject

	var body PostTaskJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostTask(ctx.Request().Context(), request.(PostTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostTask")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostTaskResponseObject); ok {
		return validResponse.VisitPostTaskResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTaskId operation middleware
func (sh *strictHandler) GetTaskId(ctx echo.Context, id string) error {
	var request GetTaskIdRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTaskId(ctx.Request().Context(), request.(GetTaskIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTaskId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTaskIdResponseObject); ok {
		return validResponse.VisitGetTaskIdResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RWwXLbNhD9Fcy2RzaSG/fCW2KrtqZprLGUUybTQYiViEQE4MXSGdXDf+8sQMmOSLfK",
	"NJdcbIoA3tvd93bBB6h8E7xDxxHKB4hVjY1Oj1fIKx0/32IM3kWUV4F8QGKLaUON2iClR4OxIhvYegcl",
	"XOcFpYn0Tq3JN+olmV+CJt6piHRvK1S0xy2AdwGhBP/xE1YMXQE1c1iy5jZeeIMjBKvVQsW0QVXeoPJr",
	"xTWexGId4wZJaKwZQr9z9q5FNb/cY7KOnx9PRybrNnJ4i27D9RDgwjtGxyqvC8o3RpXzEuCfCddQwk+T",
	"R40mvUATkSaXCLquAMK71hIaKN9LWgeUDyPVvWYOfyLXPqWPrm3k1NVsBQUsbpbp3zv5ezl7M1vN5Oer",
	"1cU1FHA9e3UJBdwsVvObt8sn4I9lmbt7vbXmFu9ajLzQu63XZuidBmPUmxFp+/OKMoAKPcKA6ijpPeBY",
	"wtnGCW8YyUdvdsMw+u1KVp+PofjvHlh7SjZKlu2TGrN8cxDk31R/Il1XQEvbEQPfvnm2HaCAtadGM5TQ",
	"kj2hqIkqMz1X2eXBr3srGe+Eyrq/AvkKY4QCkMgTFODwy4hvhNi6tRcUtrzFRwmEAuXkPVLMKZ69mL6Y",
	"Cr0P6HSwUMLL9KqAoLlOsUxS34raPqsummup0dxACQufkSEnjJFf9z6ocv/Kow5ha6t0aPIpCvV+QJ7S",
	"nXvHdV9XlanF9CKPgBTsr9Ozb6L+2sFjY+wKnaSLRrWHgba34vhEGw6RoeCy6WjaEQqLiHE+nX63+o1P",
	"kRH+19qoQ6ElhrOxka5brj3Zv3Ogv+VAj+cOIzm9VUukeyQ1S34Vwtg2jabdIVmllcMvqYqppE87W7Ef",
	"6TpBSX6cPFjTCfcGRzzZX7hzk3xMukFOo+X9qXeUlUXpAOkz3aR7xcCx+YonGhx74MPAmN9P0+PviRE1",
	"b/74oYx0Pj0fbnrrWf3uW/f/rHaFnJTtP3L8Wumsctd13T8BAAD//2WGMWq1CQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
